### ISSUE TITLE
(GLES2) Build failure on linux

### ISSUE THREAD

**Issue by orbea** [GLupeN64/GLupeN64#137]
OS: `Slackware64-current`
```
7f9e9b61367320a54dc6088d102b3a5565afc8a8 is the first bad commit
commit 7f9e9b61367320a54dc6088d102b3a5565afc8a8
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Fri Dec 2 15:59:35 2016 -0700

    Change glsm to be C++
    
    To match GLideN64, I think the C/C++ mixture might be screwing things up, but I can't be sure.
    
    This won't hurt anything anyway

:100644 100644 cdcaff97bebe7836e8e7db6f03d32b0aacd33183 112693c502e8e848d0f83424c4408acac205ed93 M	Makefile.common
:040000 040000 96ffaa9998cf3676a80f46bd40979a63c276bb6b bcfcd47be3af45bf4428a21611a72c7b2bf4c218 M	custom
```
7f9e9b61367320a54dc6088d102b3a5565afc8a8

```
/src/GLideNHQ/TextureFilters.o
In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from custom/glsm/glsm.cpp:26:
./libretro-common/include/glsym/glsym_es2.h:28:23: error: conflicting declaration ‘typedef long long int GLint64’
 typedef long long int GLint64;
                       ^
In file included from ./libretro-common/include/glsym/rglgen_headers.h:55:0,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from custom/glsm/glsm.cpp:26:
/usr/include/GLES2/gl2.h:67:25: note: previous declaration as ‘typedef khronos_int64_t GLint64’
 typedef khronos_int64_t GLint64;
                         ^
In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from custom/glsm/glsm.cpp:26:
./libretro-common/include/glsym/glsym_es2.h:32:32: error: conflicting declaration ‘typedef long long unsigned int GLuint64’
 typedef unsigned long long int GLuint64;
                                ^
In file included from ./libretro-common/include/glsym/rglgen_headers.h:55:0,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from custom/glsm/glsm.cpp:26:
/usr/include/GLES2/gl2.h:68:26: note: previous declaration as ‘typedef khronos_uint64_t GLuint64’
 typedef khronos_uint64_t GLuint64;
                          ^
In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from custom/glsm/glsm.cpp:26:
./libretro-common/include/glsym/glsym_es2.h:36:32: error: conflicting declaration ‘typedef long long unsigned int GLuint64EXT’
 typedef unsigned long long int GLuint64EXT;
                                ^
In file included from ./libretro-common/include/glsym/rglgen_headers.h:56:0,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from custom/glsm/glsm.cpp:26:
/usr/include/GLES2/gl2ext.h:2442:26: note: previous declaration as ‘typedef khronos_uint64_t GLuint64EXT’
 typedef khronos_uint64_t GLuint64EXT;
                          ^
Makefile:311: recipe for target 'custom/glsm/glsm.o' failed
make: *** [custom/glsm/glsm.o] Error 1
make: *** Waiting for unfinished jobs....
```
Build log - http://pastebin.com/SWMGw3Fr

**Comment by loganmc10** [comment]
https://github.com/libretro/libretro-common/pull/31

**Comment by orbea** [comment]
Ah, I did not see that. Thanks for reporting it. I will leave this open until that is resolved, feel free to close it sooner if you prefer.

**Comment by loganmc10** [comment]
Should be fixed now

**Comment by orbea** [comment]
It is, thanks!
